<?php
/**
 * Centralized product definitions
 * Pulls all product data from ACF globals
 */

function get_all_products($globals_id = 578) {
    $products = array(
           array(
        'name' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_name', $globals_id), 
        'id' =>  sanitize_title(get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_id', $globals_id)),
        'description' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_description', $globals_id),
        'image' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_image', $globals_id), 
        'category' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_category', $globals_id), 
        'category_url' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_category_url', $globals_id),
        'seo_title' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_seo_title', $globals_id),
        'meta_description' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_611_infeed_module_1025_kw_pn_6sn1145_1aa01_0aa2_canonical_url', $globals_id),), 
        array(
        'name' => get_field('fanuc_spindle_motor_pn_a06b1551b100_name', $globals_id), 
        'id' => sanitize_title(get_field('fanuc_spindle_motor_pn_a06b1551b100_id', $globals_id)),
        'description' => get_field('fanuc_spindle_motor_pn_a06b1551b100_description', $globals_id),
        'image' => get_field('fanuc_spindle_motor_pn_a06b1551b100_image', $globals_id), 
        'category' => get_field('fanuc_spindle_motor_pn_a06b1551b100_category', $globals_id), 
        'category_url' => get_field('fanuc_spindle_motor_pn_a06b1551b100_category_url', $globals_id),
        'seo_title' => get_field('fanuc_spindle_motor_pn_a06b1551b100_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_spindle_motor_pn_a06b1551b100_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_spindle_motor_pn_a06b1551b100_canonical_url', $globals_id),),   
        array(
        'name' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_id', $globals_id)),
        'description' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_description', $globals_id),
        'image' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_image', $globals_id), 
        'category' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_category', $globals_id), 
        'category_url' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_category_url', $globals_id),
        'seo_title' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_seo_title', $globals_id),
        'meta_description' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_nc840d_handheld_unit_pn_6fx20071ae04_canonical_url', $globals_id),),  
        array(
        'name' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_name', $globals_id), 
        'id' =>  sanitize_title(get_field('b&r_power_panel_500_pn_5pp5405853001_00_id', $globals_id)),
        'description' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_description', $globals_id),
        'image' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_image', $globals_id), 
        'category' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_category', $globals_id), 
        'category_url' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_category_url', $globals_id),
        'seo_title' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_seo_title', $globals_id),
        'meta_description' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_meta_description', $globals_id),
        'canonical_url' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_canonical_url', $globals_id),),     
        array(
        'name' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_id', $globals_id)),
        'description' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_description', $globals_id),
        'image' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_image', $globals_id), 
        'category' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_category', $globals_id), 
        'category_url' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_category_url', $globals_id),
        'seo_title' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_canonical_url', $globals_id),),   
          array(
        'name' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_id', $globals_id)),
        'description' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_description', $globals_id), 
        'image' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_image', $globals_id), 
        'category' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_category', $globals_id), 
        'category_url' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_category_url', $globals_id),
        'seo_title' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_seo_title', $globals_id),
        'meta_description' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_840d_sl_ncu_7103pn_pn_6fc53710aa300aa1_canonical_url', $globals_id),),   
        
         array(
        'name' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_id', $globals_id)),
        'description' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_description', $globals_id), 
        'image' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_image', $globals_id), 
        'category' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_category', $globals_id), 
        'category_url' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_category_url', $globals_id), 
        'seo_title' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_s7_200_cpu_226_compact_unit_pn_6es72162bd230xb0_canonical_url', $globals_id),),
    array(
        'name' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_single_motor_module_pn_6sl31201te210aa4_id', $globals_id)),
        'description' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_description', $globals_id), 
        'image' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_image', $globals_id), 
        'category' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_category', $globals_id), 
        'category_url' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_category_url', $globals_id),
        'seo_title' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_seo_title', $globals_id),
        'meta_description' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_single_motor_module_pn_6sl31201te210aa4_canonical_url', $globals_id),),        
    array(
        'name' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_id', $globals_id)),
        'description' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_description', $globals_id),
        'image' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_category_image', $globals_id), 
        'category' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_category', $globals_id), 
        'category_url' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_category_url', $globals_id),
        'seo_title' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_seo_title', $globals_id),
        'meta_description' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_power_module_1axis_80a_pn_6sn11231aa000da1_canonical_url', $globals_id),),       
    array(
        'name' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_id', $globals_id)),
        'description' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_description', $globals_id),
        'image' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_image', $globals_id), 
        'category' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_category', $globals_id), 
        'category_url' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_category_url', $globals_id),
        'seo_title' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_seo_title', $globals_id),
        'meta_description' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_servo_motor_cliq_connect_pn_1ft70845ac711dh1_canonical_url', $globals_id),),    
    array(
        'name' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_name', $globals_id), 
        'id' => sanitize_title(get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_id', $globals_id)),
        'description' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_description', $globals_id),
        'image' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_image', $globals_id), 
        'category' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_category', $globals_id), 
        'category_url' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_category_url', $globals_id),
        'seo_title' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_seo_title', $globals_id),
        'meta_description' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_meta_description', $globals_id),
        'canonical_url' => get_field('allen_bradley_servo_motor_pn_mplb310psj72aa_canonical_url', $globals_id),),      
     array(
        'name' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_id', $globals_id)),
        'description' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_description', $globals_id),
        'image' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_image', $globals_id), 
        'category' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_category', $globals_id), 
        'category_url' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_category_url', $globals_id),
        'seo_title' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_hmi_pcu_50_pn_6fc52100df252aa0_canonical_url', $globals_id),),      
    array(
        'name' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_name', $globals_id), 
        'id' => sanitize_title(get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_id', $globals_id)),
        'description' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_description', $globals_id),
        'image' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_image', $globals_id), 
        'category' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_category', $globals_id), 
        'category_url' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_category_url', $globals_id),
        'seo_title' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_seo_title', $globals_id),
        'meta_description' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_meta_description', $globals_id),
        'canonical_url' => get_field('tripp_lite_smart_online_ups_power_module_model_su10000rt3upm_canonical_url', $globals_id),),      
    array(
        'name' => get_field('siemens_line_filter_pn_6sl30000be236aa0_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_line_filter_pn_6sl30000be236aa0_id', $globals_id)),
        'description' => get_field('siemens_line_filter_pn_6sl30000be236aa0_description', $globals_id),
        'image' => get_field('siemens_line_filter_pn_6sl30000be236aa0_image', $globals_id), 
        'category' => get_field('siemens_line_filter_pn_6sl30000be236aa0_category', $globals_id), 
        'category_url' => get_field('siemens_line_filter_pn_6sl30000be236aa0_category_url', $globals_id),
        'seo_title' => get_field('siemens_line_filter_pn_6sl30000be236aa0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_line_filter_pn_6sl30000be236aa0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_line_filter_pn_6sl30000be236aa0_canonical_url', $globals_id),),      
     array(
        'name' => get_field('sick_light_cutrain_c4000_pn_xc40e_0603a0a0aaa0_name', $globals_id), 
        'id' => sanitize_title(get_field('sick_light_cutrain_c4000_pn_xc40e_0603a0a0aaa0_id', $globals_id)),
        'description' => get_field('sick_light_cutrain_c4000_pn_xc40e_0603a0a0aaa0_description', $globals_id),
        'image' => get_field('sick_light_cutrain_c4000_pn_xc40e_0603a0a0aaa0_image', $globals_id), 
        'category' => get_field('sick_light_cutrain_c4000_pn_xc40e_0603a0a0aaa0_category', $globals_id), 
        'category_url' => get_field('sick_light_cutrain_c4000_pn_xc40e_0603a0a0aaa0_category_url', $globals_id),
        'seo_title' => get_field('sick_light_cutrain_c4000_pn_xc40e_0603a0a0aaa0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_line_filter_pn_6sl30000be236aa0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_line_filter_pn_6sl30000be236aa0_canonical_url', $globals_id),), 
    array(
        'name' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_id', $globals_id)),
        'description' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_description', $globals_id),
        'image' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_image', $globals_id), 
        'category' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_category', $globals_id), 
        'category_url' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_category_url', $globals_id),
        'seo_title' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_canonical_url', $globals_id),),     
    array(
        'name' => get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_id', $globals_id)),
        'description' => get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_description', $globals_id),
        'image' => get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_image', $globals_id), 
        'category' => get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_category', $globals_id), 
        'category_url' => get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_category_url', $globals_id),
        'seo_title' => get_field('siemens_industrial_computer_panel_pc_670_pn_6av7623_0ab22_4ce0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_handheld_terminal_ht_6_pn_6fc5403_0aa10_0aa0_canonical_url', $globals_id),), 
    array(
        'name' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_id', $globals_id)),
        'description' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_description', $globals_id),
        'image' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_image', $globals_id), 
        'category' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_category', $globals_id), 
        'category_url' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_category_url', $globals_id),
        'seo_title' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_seo_title', $globals_id),
        'meta_description' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_s5_s5_95u_compact_unit_pn_6es5095_8ma04_canonical_url', $globals_id),), 
     array(
        'name' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_id', $globals_id)),
        'description' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_description', $globals_id),
        'image' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_image', $globals_id), 
        'category' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_category', $globals_id), 
        'category_url' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_category_url', $globals_id),
        'seo_title' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_840dde_ncu_5722_w_software_card_pn_6fc5357_0bb21_0ae0_canonical_url', $globals_id),), 
    array(
        'name' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_id', $globals_id)),
        'description' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_description', $globals_id),
        'image' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_image', $globals_id), 
        'category' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_category', $globals_id), 
        'category_url' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_category_url', $globals_id),
        'seo_title' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_seo_title', $globals_id),
        'meta_description' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_canonical_url', $globals_id),),                  
    array(
        'name' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_name', $globals_id), 
        'id' => sanitize_title(get_field('sick_safety_laser_scanner_pn_s30a6011ba_id', $globals_id)),
        'description' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_description', $globals_id),
        'image' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_image', $globals_id), 
        'category' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_category', $globals_id), 
        'category_url' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_category_url', $globals_id),
        'seo_title' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_seo_title', $globals_id),
        'meta_description' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_meta_description', $globals_id),
        'canonical_url' => get_field('sick_safety_laser_scanner_pn_s30a6011ba_canonical_url', $globals_id),),                  
    array(
        'name' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_name', $globals_id), 
        'id' =>  sanitize_title(get_field('siemens_signal_cable_pn_6fx80022eq101ca0_id', $globals_id)),
        'description' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_description', $globals_id),
        'image' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_image', $globals_id), 
        'category' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_category', $globals_id), 
        'category_url' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_category_url', $globals_id),
        'seo_title' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_signal_cable_pn_6fx80022eq101ca0_canonical_url', $globals_id),),       
    array(
        'name' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_name', $globals_id), 
        'id' => sanitize_title(get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_id', $globals_id)),
        'description' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_description', $globals_id),
        'image' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_image', $globals_id), 
        'category' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_category', $globals_id), 
        'category_url' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_category_url', $globals_id),
        'seo_title' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_fm_nc810dde840dde_19_machine_control_panel_pn_6fc5203_0ad10_0aa0_canonical_url', $globals_id),),         
     array(
        'name' => get_field('siemens_operator_panel_op_77b_pn_6av6641_0ca01_0ax1_name', $globals_id), 
        'id' =>  sanitize_title(get_field('siemens_operator_panel_op_77b_pn_6av6641_0ca01_0ax1_id', $globals_id)),
        'description' => get_field('siemens_operator_panel_op_77b_pn_6av6641_0ca01_0ax1_description', $globals_id),
        'image' => get_field('siemens_operator_panel_op_77b_pn_6av6641_0ca01_0ax1_image', $globals_id), 
        'category' => get_field('siemens_operator_panel_op_77b_pn_6av6641_0ca01_0ax1_category', $globals_id), 
        'category_url' => get_field('siemens_operator_panel_op_77b_pn_6av6641_0ca01_0ax1_category_url', $globals_id),
        'seo_title' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_seo_title', $globals_id),
        'meta_description' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_operator_panel_with_membrane_keys_pn_6fc5203_0af02_0aa1_canonical_url', $globals_id),), 
    array(
        'name' => get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_name', $globals_id), 
        'id' =>  sanitize_title(get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_id', $globals_id)),
        'description' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_description', $globals_id),
        'image' => get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_image', $globals_id), 
        'category' => get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_category', $globals_id), 
        'category_url' => get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_category_url', $globals_id),
        'seo_title' => get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_seo_title', $globals_id),
        'meta_description' => get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_meta_description', $globals_id),
        'canonical_url' => get_field('indramat_digital_ac_servo_controller_pn_dds021_w100_d_canonical_url', $globals_id),),  
        //////
    array(
        'name' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_id', $globals_id)),
        'description' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_description', $globals_id),
        'image' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_image', $globals_id), 
        'category' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_category', $globals_id), 
        'category_url' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_category_url', $globals_id),
        'seo_title' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_servo_unit_ac_2030_pn_a06b_6058_h006_canonical_url', $globals_id),),      
      array(
        'name' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_name', $globals_id), 
        'id' =>  sanitize_title(get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_id', $globals_id)),
        'description' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_description', $globals_id),
        'image' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_image', $globals_id), 
        'category' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_category', $globals_id), 
        'category_url' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_category', $globals_id),
        'seo_title' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_seo_title', $globals_id),
        'meta_description' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_meta_description', $globals_id),
        'canonical_url' => get_field('abb_baldor_ac_servo_motor_pn_bsm80n_275bf_canonical_url', $globals_id),),    
        /////
    array(
        'name' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_id', $globals_id)),
        'description' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_description', $globals_id),
        'image' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_image', $globals_id), 
        'category' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_category', $globals_id), 
        'category_url' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_category_url', $globals_id),
        'seo_title' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_hand_wheel_manual_pulse_generator_pn_a860_0203_t010_canonical_url', $globals_id),),     
    array(
        'name' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_name', $globals_id), 
        'id' =>  sanitize_title(get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_id', $globals_id)),
        'description' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_description', $globals_id),
        'image' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_image', $globals_id), 
        'category' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_category', $globals_id), 
        'category_url' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_category_url', $globals_id),
        'seo_title' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_seo_title', $globals_id),
        'meta_description' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_meta_description', $globals_id),
        'canonical_url' => get_field('allen_bradley_1388_dc_servo_controller_pn_1388_av60_canonical_url', $globals_id),),       
    array(
        'name' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_name', $globals_id), 
        'id' =>  sanitize_title(get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_id', $globals_id)),
        'description' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_description', $globals_id),
        'image' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_image', $globals_id), 
        'category' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_category', $globals_id), 
        'category_url' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_category_url', $globals_id),
        'seo_title' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_seo_title', $globals_id),
        'meta_description' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_plc_cpu_sr60_pn_6es7288_1sr60_0aa0_canonical_url', $globals_id),),
      array(
        'name' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_id', $globals_id)),
        'description' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_description', $globals_id),
        'image' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_image', $globals_id), 
        'category' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_category', $globals_id), 
        'category_url' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_category_url', $globals_id),
        'seo_title' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_servo_motor_wbrake_pn_a06b_0514_b172_7000_canonical_url', $globals_id),),           
     array(
        'name' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_id', $globals_id)),
        'description' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_description', $globals_id),
        'image' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_image', $globals_id), 
        'category' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_category', $globals_id), 
        'category_url' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_category_url', $globals_id),
        'seo_title' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_servo_unit_ac_05_pn_a06b_6050_h102_canonical_url', $globals_id),), 
    array(
        'name' => get_field('allen_bradley_1391_ac_servo_controller_pn_1391b_aa4_name', $globals_id), 
        'id' =>  sanitize_title(get_field('allen_bradley_1391_ac_servo_controller_pn_1391b_aa4_id', $globals_id)),
        'description' => get_field('allen_bradley_1391_ac_servo_controller_pn_1391b_aa4_description', $globals_id),
        'image' => get_field('allen_bradley_1391_ac_servo_controller_pn_1391b_aa4_image', $globals_id), 
        'category' => get_field('allen_bradley_1391_ac_servo_controller_pn_1391b_aa4_category', $globals_id), 
        'category_url' => get_field('allen_bradley_1391_ac_servo_controller_pn_1391b_aa4_category_url', $globals_id),
        'seo_title' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_seo_title', $globals_id),
        'meta_description' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_meta_description', $globals_id),
        'canonical_url' => get_field('b&r_power_panel_500_pn_5pp5405853001_00_canonical_url', $globals_id),),  
    array(
        'name' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_id', $globals_id)),
        'description' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_description', $globals_id),
        'image' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_image', $globals_id), 
        'category' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_category', $globals_id), 
        'category_url' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_category_url', $globals_id),
        'seo_title' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_series_16i_t_series_operator_panel_pn_a02b_0265_c066_canonical_url', $globals_id),), 
    array(
        'name' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_pulse_encoder_pn_a860_2020_t301_id', $globals_id)),
        'description' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_description', $globals_id),
        'image' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_image', $globals_id), 
        'category' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_category', $globals_id), 
        'category_url' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_category_url', $globals_id),
        'seo_title' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_pulse_encoder_pn_a860_2020_t301_canonical_url', $globals_id),),           
    array(
        'name' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_id', $globals_id), 
        'id' =>  sanitize_title(get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_price', $globals_id)),
        'description' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_description', $globals_id),
        'image' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_image', $globals_id), 
        'category' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_category', $globals_id), 
        'category_url' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_category_url', $globals_id),
        'seo_title' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_seo_title', $globals_id),
        'meta_description' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_meta_description', $globals_id),
        'canonical_url' => get_field('indramat_digital_ac_servo_controller_pn_dds031_w050_d_canonical_url', $globals_id),),  
    array(
        'name' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_name', $globals_id), 
        'id' =>  sanitize_title(get_field('fanuc_servo_amp_pn_a06b_6096_h208_id', $globals_id)),
        'description' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_description', $globals_id),
        'image' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_image', $globals_id), 
        'category' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_category', $globals_id), 
        'category_url' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_category_url', $globals_id),
        'seo_title' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_seo_title', $globals_id),
        'meta_description' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_meta_description', $globals_id),
        'canonical_url' => get_field('fanuc_servo_amp_pn_a06b_6096_h208_canonical_url', $globals_id),),    
    array(
        'name' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_name', $globals_id), 
        'id' =>  sanitize_title(get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_id', $globals_id)),
        'description' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_description', $globals_id),
        'image' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_image', $globals_id), 
        'category' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_category', $globals_id), 
        'category_url' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_category_url', $globals_id),
        'seo_title' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_seo_title', $globals_id),
        'meta_description' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_meta_description', $globals_id),
        'canonical_url' => get_field('siemens_servo_motor_water_cooled_pn_1ft7084_5wf71_1mh1_canonical_url', $globals_id),)
    );

    return array_filter($products, fn($p) => !empty($p['name']));
}